"use client";

import { useState, type FormEvent } from "react";
import { toast } from "react-toastify";
import { Button, ConfirmModal, Input, Modal, Textarea } from "@/components/ui";
import { eventsApi } from "@/lib/api/events";
import type { EventCategory, EventSpeaker } from "@/types/events";

type Target = { kind: "speaker" | "category"; id: string; name: string };
export default function RelatedManagers({ open, onClose, speakers, categories, onChanged }: { open: boolean; onClose: () => void; speakers: EventSpeaker[]; categories: EventCategory[]; onChanged: () => Promise<void> }) {
  const [tab, setTab] = useState<"speakers" | "categories">("speakers");
  const [editingSpeaker, setEditingSpeaker] = useState<EventSpeaker | null>(null);
  const [speaker, setSpeaker] = useState({ name: "", title: "", bio: "" });
  const [editingCategory, setEditingCategory] = useState<EventCategory | null>(null);
  const [categoryName, setCategoryName] = useState("");
  const [pending, setPending] = useState(false);
  const [target, setTarget] = useState<Target | null>(null);

  const resetSpeaker = () => { setEditingSpeaker(null); setSpeaker({ name: "", title: "", bio: "" }); };
  const resetCategory = () => { setEditingCategory(null); setCategoryName(""); };
  const saveSpeaker = async (event: FormEvent) => { event.preventDefault(); if (!speaker.name.trim()) return; setPending(true); try { if (editingSpeaker) await eventsApi.updateSpeaker(editingSpeaker._id, speaker); else await eventsApi.createSpeaker(speaker); toast.success(editingSpeaker ? "Speaker updated." : "Speaker created."); resetSpeaker(); await onChanged(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Speaker could not be saved."); } finally { setPending(false); } };
  const saveCategory = async (event: FormEvent) => { event.preventDefault(); if (!categoryName.trim()) return; setPending(true); try { if (editingCategory) await eventsApi.updateCategory(editingCategory._id, categoryName.trim()); else await eventsApi.createCategory(categoryName.trim()); toast.success(editingCategory ? "Category updated." : "Category created."); resetCategory(); await onChanged(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Category could not be saved."); } finally { setPending(false); } };
  const remove = async () => { if (!target) return; setPending(true); try { if (target.kind === "speaker") await eventsApi.deleteSpeaker(target.id); else await eventsApi.deleteCategory(target.id); toast.success(`${target.kind === "speaker" ? "Speaker" : "Category"} deleted.`); setTarget(null); await onChanged(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "The record could not be deleted."); } finally { setPending(false); } };

  return <><Modal open={open} onClose={pending ? () => {} : onClose} closeOnBackdrop={!pending} title="Speakers and categories" description="Manage reusable event details without losing an event draft.">
    <div className="mb-5 grid grid-cols-2 rounded-xl bg-[var(--color-surface-muted)] p-1"><button type="button" onClick={() => setTab("speakers")} className={`min-h-11 cursor-pointer rounded-lg text-sm font-medium ${tab === "speakers" ? "bg-[var(--color-surface)] text-[var(--color-primary)]" : "text-[var(--color-muted)]"}`}>Speakers</button><button type="button" onClick={() => setTab("categories")} className={`min-h-11 cursor-pointer rounded-lg text-sm font-medium ${tab === "categories" ? "bg-[var(--color-surface)] text-[var(--color-primary)]" : "text-[var(--color-muted)]"}`}>Categories</button></div>
    {tab === "speakers" ? <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(260px,.8fr)]"><div className="space-y-2">{speakers.length ? speakers.map((item) => <div key={item._id} className="flex items-start justify-between gap-3 rounded-xl border border-[var(--color-border)] p-3"><div><p className="font-medium">{item.name}</p><p className="text-sm text-[var(--color-muted)]">{item.title || item.bio || "Speaker"}</p></div><div className="flex gap-2"><Button variant="secondary" className="min-h-9 px-3" onClick={() => { setEditingSpeaker(item); setSpeaker({ name: item.name, title: item.title ?? "", bio: item.bio ?? "" }); }}>Edit</Button><Button variant="danger" className="min-h-9 px-3" onClick={() => setTarget({ kind: "speaker", id: item._id, name: item.name })}>Delete</Button></div></div>) : <p className="text-sm text-[var(--color-muted)]">No speakers yet.</p>}</div><form onSubmit={saveSpeaker} className="space-y-3 rounded-xl bg-[var(--color-surface-muted)] p-4"><h3 className="font-semibold">{editingSpeaker ? "Edit speaker" : "Add speaker"}</h3><Input aria-label="Speaker name" placeholder="Name" value={speaker.name} onChange={(e) => setSpeaker((value) => ({ ...value, name: e.target.value }))} required /><Input aria-label="Speaker title" placeholder="Title (optional)" value={speaker.title} onChange={(e) => setSpeaker((value) => ({ ...value, title: e.target.value }))} /><Textarea aria-label="Speaker biography" placeholder="Biography (optional)" value={speaker.bio} onChange={(e) => setSpeaker((value) => ({ ...value, bio: e.target.value }))} /><div className="flex gap-2"><Button type="submit" loading={pending}>{editingSpeaker ? "Save" : "Add"}</Button>{editingSpeaker && <Button type="button" variant="secondary" onClick={resetSpeaker}>Cancel</Button>}</div></form></div>
    : <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(260px,.8fr)]"><div className="space-y-2">{categories.length ? categories.map((item) => <div key={item._id} className="flex items-center justify-between gap-3 rounded-xl border border-[var(--color-border)] p-3"><p className="font-medium">{item.name}</p><div className="flex gap-2"><Button variant="secondary" className="min-h-9 px-3" onClick={() => { setEditingCategory(item); setCategoryName(item.name); }}>Edit</Button><Button variant="danger" className="min-h-9 px-3" onClick={() => setTarget({ kind: "category", id: item._id, name: item.name })}>Delete</Button></div></div>) : <p className="text-sm text-[var(--color-muted)]">No categories yet.</p>}</div><form onSubmit={saveCategory} className="space-y-3 rounded-xl bg-[var(--color-surface-muted)] p-4"><h3 className="font-semibold">{editingCategory ? "Edit category" : "Add category"}</h3><Input aria-label="Category name" placeholder="Category name" value={categoryName} onChange={(e) => setCategoryName(e.target.value)} required /><div className="flex gap-2"><Button type="submit" loading={pending}>{editingCategory ? "Save" : "Add"}</Button>{editingCategory && <Button type="button" variant="secondary" onClick={resetCategory}>Cancel</Button>}</div></form></div>}
  </Modal><ConfirmModal open={Boolean(target)} onClose={() => setTarget(null)} onConfirm={remove} pending={pending} title={`Delete ${target?.kind ?? "record"}?`} description={`Delete “${target?.name ?? "this record"}”? Existing events may still reference it.`} confirmLabel="Delete" /></>;
}