import { forwardRef, type ButtonHTMLAttributes, type InputHTMLAttributes, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";
import { cn } from "./utils";
const field = "w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] px-3 text-sm text-[var(--color-text)] outline-none transition focus:border-[var(--color-primary)] focus:ring-4 focus:ring-[var(--color-primary-soft)] disabled:cursor-not-allowed disabled:opacity-60";
type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "danger"; loading?: boolean };
export function Button({ variant = "primary", loading, disabled, className, children, ...props }: ButtonProps) { const variants = { primary: "bg-[var(--color-primary)] text-white hover:bg-[var(--color-primary-hover)]", secondary: "border border-[var(--color-border)] bg-[var(--color-surface)] text-[var(--color-text)] hover:bg-[var(--color-surface-muted)]", danger: "bg-[var(--color-danger)] text-white hover:opacity-90" }; return <button className={cn("inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-primary-soft)] disabled:cursor-not-allowed disabled:opacity-60", variants[variant], className)} disabled={disabled || loading} aria-busy={loading || undefined} {...props}>{loading && <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" aria-hidden="true" />}{children}</button>; }
export function IconButton({ "aria-label": label, className, ...props }: ButtonHTMLAttributes<HTMLButtonElement>) { if (!label) throw new Error("IconButton requires an aria-label"); return <button aria-label={label} className={cn("grid h-11 w-11 cursor-pointer place-items-center rounded-xl border border-[var(--color-border)] transition hover:bg-[var(--color-surface-muted)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-primary-soft)]", className)} {...props} />; }
export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(({ className, ...props }, ref) => <input ref={ref} className={cn(field, "h-11", className)} {...props} />); Input.displayName = "Input";
export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(({ className, ...props }, ref) => <select ref={ref} className={cn(field, "h-11 cursor-pointer", className)} {...props} />); Select.displayName = "Select";
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(({ className, ...props }, ref) => <textarea ref={ref} className={cn(field, "min-h-28 py-3", className)} {...props} />); Textarea.displayName = "Textarea";
export function Checkbox({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input type="checkbox" className={cn("h-5 w-5 cursor-pointer rounded border-[var(--color-border)] accent-[var(--color-primary)]", className)} {...props} />; }
export function Switch({ checked, onChange, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <label className="relative inline-flex min-h-11 cursor-pointer items-center"><input type="checkbox" role="switch" className="peer sr-only" checked={checked} onChange={onChange} {...props} /><span className="h-6 w-11 rounded-full bg-gray-300 transition peer-checked:bg-[var(--color-primary)] peer-focus-visible:ring-4 peer-focus-visible:ring-[var(--color-primary-soft)] after:absolute after:left-1 after:top-1/2 after:h-4 after:w-4 after:-translate-y-1/2 after:rounded-full after:bg-white after:transition peer-checked:after:translate-x-5" /></label>; }
