"use client";
import { useEffect, useState, type ReactNode } from "react";
import { HiOutlineInbox, HiOutlineMagnifyingGlass, HiOutlineExclamationTriangle } from "react-icons/hi2";
import { Button, Input, Select } from "./controls";
import { cn } from "./utils";
export function PageHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <header className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h2>{description && <p className="mt-2 text-[var(--color-muted)]">{description}</p>}</div>{action}</header>; }
export function StatCard({ label, value, description, icon }: { label: string; value: ReactNode; description?: string; icon?: ReactNode }) { return <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><div className="flex justify-between gap-4"><p className="text-sm text-[var(--color-muted)]">{label}</p>{icon}</div><p className="mt-3 text-3xl font-semibold">{value}</p>{description && <p className="mt-2 text-sm text-[var(--color-muted)]">{description}</p>}</section>; }
export type Column<T> = { key: string; header: ReactNode; render: (row: T) => ReactNode; className?: string };
export function DataTable<T>({ columns, rows, rowKey, caption }: { columns: Column<T>[]; rows: T[]; rowKey: (row: T) => string; caption: string }) { return <div className="overflow-x-auto rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)]"><table className="w-full min-w-[640px] text-left text-sm"><caption className="sr-only">{caption}</caption><thead className="bg-[var(--color-surface-muted)] text-[var(--color-muted)]"><tr>{columns.map((column) => <th key={column.key} className={cn("px-4 py-3 font-medium", column.className)}>{column.header}</th>)}</tr></thead><tbody className="divide-y divide-[var(--color-border)]">{rows.map((row) => <tr key={rowKey(row)}>{columns.map((column) => <td key={column.key} className={cn("px-4 py-3", column.className)}>{column.render(row)}</td>)}</tr>)}</tbody></table></div>; }
export function Pagination({ page, totalPages, onPageChange }: { page: number; totalPages: number; onPageChange: (page: number) => void }) { return <nav aria-label="Pagination" className="flex items-center justify-between gap-3"><Button variant="secondary" disabled={page <= 1} onClick={() => onPageChange(page - 1)}>Previous</Button><span className="text-sm text-[var(--color-muted)]">Page {page} of {Math.max(1, totalPages)}</span><Button variant="secondary" disabled={page >= totalPages} onClick={() => onPageChange(page + 1)}>Next</Button></nav>; }
export function SearchField({ value, onChange, onDebouncedChange, delay = 300, className, ...props }: React.ComponentProps<typeof Input> & { value: string; onChange: React.ChangeEventHandler<HTMLInputElement>; onDebouncedChange?: (value: string) => void; delay?: number }) { useEffect(() => { const timer = setTimeout(() => onDebouncedChange?.(value), delay); return () => clearTimeout(timer); }, [value, delay, onDebouncedChange]); return <label className="relative block"><span className="sr-only">Search</span><HiOutlineMagnifyingGlass className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-[var(--color-muted)]" /><Input type="search" value={value} onChange={onChange} className={cn("pl-10", className)} {...props} /></label>; }
export function FilterBar({ children }: { children: ReactNode }) { return <div className="flex flex-wrap items-end gap-3 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4">{children}</div>; }
export function Skeleton({ className }: { className?: string }) { return <div aria-hidden="true" className={cn("animate-pulse rounded-xl bg-[var(--color-placeholder-fill)]", className ?? "h-12 w-full")} />; }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <section className="grid min-h-56 place-items-center rounded-2xl border border-dashed border-[var(--color-border)] p-8 text-center"><div><HiOutlineInbox className="mx-auto h-8 w-8 text-[var(--color-muted)]" /><h3 className="mt-3 font-semibold">{title}</h3>{description && <p className="mt-1 text-sm text-[var(--color-muted)]">{description}</p>}{action && <div className="mt-4">{action}</div>}</div></section>; }
export function ErrorState({ title = "Something went wrong", description, onRetry }: { title?: string; description: string; onRetry?: () => void }) { return <section role="alert" className="grid min-h-56 place-items-center rounded-2xl border border-[var(--color-danger)] bg-[var(--color-danger-soft)] p-8 text-center"><div><HiOutlineExclamationTriangle className="mx-auto h-8 w-8 text-[var(--color-danger)]" /><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-1 text-sm text-[var(--color-muted)]">{description}</p>{onRetry && <Button className="mt-4" onClick={onRetry}>Try again</Button>}</div></section>; }
export function StatusPill({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "success" | "warning" | "danger" }) { const styles = { neutral: "bg-[var(--color-surface-muted)] text-[var(--color-muted)]", success: "bg-[var(--color-success-soft)] text-[var(--color-success)]", warning: "bg-[var(--color-warning-soft)] text-[var(--color-warning)]", danger: "bg-[var(--color-danger-soft)] text-[var(--color-danger)]" }; return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-medium", styles[tone])}>{children}</span>; }
export function DropdownMenu({ label, children }: { label: string; children: ReactNode }) { const [open, setOpen] = useState(false); return <div className="relative"><Button variant="secondary" aria-expanded={open} aria-haspopup="menu" onClick={() => setOpen((v) => !v)}>{label}</Button>{open && <div role="menu" className="absolute right-0 z-20 mt-2 min-w-44 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-1 shadow-sm" onClick={() => setOpen(false)}>{children}</div>}</div>; }
export { Select };
