"use client";

import { useEffect, useState, type FormEvent } from "react";
import { HiOutlineKey, HiOutlineShieldCheck } from "react-icons/hi2";
import { toast } from "react-toastify";
import { Button, Input, Modal, PageHeader, PageSection } from "@/components/ui";
import { passwordSecurityApi } from "@/lib/api/settings";
import { isStrongPassword } from "@/lib/validators";
import type { ApiResult } from "@/types/api";

function requestError(reason: unknown, fallback: string) { return reason instanceof Error ? reason.message : fallback; }
function record(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === "object" && !Array.isArray(value); }
function needsReauthentication(result: ApiResult<unknown>) { const sources = [result.data, result.metadata].filter(record); return sources.some((source) => source.requiresReauthentication === true || source.requireReauth === true || source.sessionInvalidated === true || source.logout === true) || /sign in again|log in again|re-?authenticate/i.test(result.message || ""); }

export default function PasswordSecurityPage() {
  const [open, setOpen] = useState(false);
  return <div className="space-y-6 text-[var(--color-text)]"><PageSection><PageHeader title="Password security" description="Change your administrator password using a short-lived email verification code." /></PageSection><PageSection delay={.05} className="max-w-2xl rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[var(--color-primary-soft)] text-[var(--color-primary)]"><HiOutlineShieldCheck className="h-6 w-6" /></span><div><h2 className="text-lg font-semibold">Administrator password</h2><p className="mt-1 text-sm leading-6 text-[var(--color-muted)]">Request a one-time code, then confirm your current password and choose a new one. Codes are valid for 10 minutes.</p></div></div><Button className="mt-6" onClick={() => setOpen(true)}><HiOutlineKey className="h-4 w-4" />Change password</Button></PageSection><PasswordModal open={open} onClose={() => setOpen(false)} /></div>;
}

function PasswordModal({ open, onClose }: { open: boolean; onClose: () => void }) { if (!open) return null; return <PasswordForm onClose={onClose} />; }
function PasswordForm({ onClose }: { onClose: () => void }) {
  const [form, setForm] = useState({ oldPassword: "", newPassword: "", confirmation: "", otp: "" });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [otpRequested, setOtpRequested] = useState(false);
  const [cooldown, setCooldown] = useState(0);
  const [requesting, setRequesting] = useState(false);
  const [pending, setPending] = useState(false);
  useEffect(() => { if (cooldown <= 0) return; const timer = window.setInterval(() => setCooldown((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [cooldown]);
  const update = (key: keyof typeof form, value: string) => { setForm((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: "", request: "" })); };
  const requestOtp = async () => { if (requesting || cooldown > 0) return; setRequesting(true); setErrors((current) => ({ ...current, request: "" })); try { const result = await passwordSecurityApi.requestOtp(); setOtpRequested(true); setCooldown(60); toast.success(result.message || "Verification code sent to your email."); } catch (reason) { setErrors((current) => ({ ...current, request: requestError(reason, "A verification code could not be requested.") })); } finally { setRequesting(false); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); const next: Record<string, string> = {}; if (!form.oldPassword) next.oldPassword = "Enter your current password."; if (!isStrongPassword(form.newPassword)) next.newPassword = "Use at least 8 characters, subject to the backend password policy."; if (form.newPassword === form.oldPassword) next.newPassword = "Choose a password different from your current password."; if (form.confirmation !== form.newPassword) next.confirmation = "Password confirmation does not match."; if (!form.otp.trim()) next.otp = "Enter the emailed verification code."; setErrors(next); if (Object.keys(next).length) return; setPending(true); try { const result = await passwordSecurityApi.change({ oldPassword: form.oldPassword, newPassword: form.newPassword, otp: form.otp.trim() }); const reauthenticate = needsReauthentication(result); setForm({ oldPassword: "", newPassword: "", confirmation: "", otp: "" }); onClose(); toast.success(result.message || "Administrator password changed."); if (reauthenticate) { await fetch("/api/auth/logout", { method: "POST", credentials: "same-origin" }); window.location.replace("/"); } } catch (reason) { setErrors((current) => ({ ...current, request: requestError(reason, "The password could not be changed. Check the current password and verification code.") })); } finally { setPending(false); } };
  const locked = pending || requesting;
  return <Modal open onClose={locked ? () => undefined : onClose} closeOnBackdrop={!locked} title="Change administrator password" description="Passwords and verification codes remain only in this form and are cleared after success." footer={<><Button variant="secondary" onClick={onClose} disabled={locked}>Cancel</Button><Button type="submit" form="password-security-form" loading={pending}>Change password</Button></>}><form id="password-security-form" onSubmit={submit} className="space-y-4"><div className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface-muted)] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">Email verification code</p><p className="mt-1 text-xs text-[var(--color-muted)]">The backend emails a code valid for 10 minutes.</p></div><Button type="button" variant="secondary" loading={requesting} disabled={pending || cooldown > 0} onClick={() => void requestOtp()}>{otpRequested ? cooldown > 0 ? `Resend in ${cooldown}s` : "Resend code" : "Request code"}</Button></div></div><Field label="Current password" error={errors.oldPassword}><Input type="password" autoComplete="current-password" value={form.oldPassword} onChange={(event) => update("oldPassword", event.target.value)} disabled={locked} /></Field><Field label="New password" error={errors.newPassword}><Input type="password" autoComplete="new-password" value={form.newPassword} onChange={(event) => update("newPassword", event.target.value)} disabled={locked} /></Field><Field label="Confirm new password" error={errors.confirmation}><Input type="password" autoComplete="new-password" value={form.confirmation} onChange={(event) => update("confirmation", event.target.value)} disabled={locked} /></Field><Field label="Verification code" error={errors.otp}><Input inputMode="numeric" autoComplete="one-time-code" value={form.otp} onChange={(event) => update("otp", event.target.value)} disabled={locked} /></Field>{errors.request && <p role="alert" className="rounded-xl bg-[var(--color-danger-soft)] p-3 text-sm text-[var(--color-danger)]">{errors.request}</p>}</form></Modal>;
}
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-medium">{label}<div className="mt-2">{children}</div>{error && <span className="mt-1 block text-sm text-[var(--color-danger)]">{error}</span>}</label>; }